spring:
  application:
    name: AuthenticationAPI
  security:
    user:
      name: USER001
      password: 122345
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ${JWT_SECRET}
  expiration: 1800000
role:
  server:
    url: ${ROLE_SERVER_URL}
server:
  port: ${SERVER_PORT:8081}
  address: 0.0.0.0


